In [5]:
import numpy as np

In [6]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((3,5), 3.14 )

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.random.random((3,3))

array([[0.74464173, 0.76049285, 0.04386529],
       [0.52809769, 0.45429446, 0.72899319],
       [0.57435941, 0.4462096 , 0.87731442]])

In [14]:
np.random.randint(0,10, (3,3))

array([[3, 5, 4],
       [3, 4, 2],
       [8, 8, 0]], dtype=int32)

In [26]:
np.random.randint(0, 20, (10,10), dtype='int32')

array([[14,  4,  4, 16,  4,  0, 18,  1, 19, 11],
       [11,  7, 18,  5,  6, 15, 13, 17,  4, 13],
       [18,  5, 14, 14,  6,  4,  9, 12,  2,  2],
       [13,  3,  7, 13, 16,  2, 19,  5,  5,  9],
       [18, 16, 10, 13, 12, 16, 12, 11,  8,  1],
       [13, 13, 19, 10, 17, 15,  6,  0, 16, 12],
       [ 4, 17,  8, 10, 17,  4,  0, 16, 16,  3],
       [ 4,  2,  7, 18, 18, 12, 17,  5,  2, 15],
       [ 4, 11, 16, 19, 11, 10, 14,  3,  1, 16],
       [16, 18, 14, 13,  3,  8, 13,  7,  2, 14]], dtype=int32)

In [27]:
import pandas as pd
import numpy as np

dados = {

    'Nome': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eduardo'],

    'Idade': [28, 34, 29, None, 42],

    'Cidade': ['São Paulo', 'Rio de Janeiro', None, 'Curitiba', 'Belo Horizonte'],

    'Vendas': [150, 200, 300, 400, None]

}

##  1 Crie um DataFrame com base nos dados fornecidos;

In [28]:
df = pd.DataFrame(dados)

## 2 Filtre os clientes que têm mais de 30 anos;

In [29]:
clientes_30_anos = df[df['Idade'] > 30]
print(clientes_30_anos)

      Nome  Idade          Cidade  Vendas
1    Bruno   34.0  Rio de Janeiro   200.0
4  Eduardo   42.0  Belo Horizonte     NaN


## 3. Calcular a média de idade dos clientes (ignorando valores nulos)

In [33]:
media_idade_clientes = df['Idade'].mean()
print("A média de idade de todos os clientes é de", media_idade_clientes, "anos")

A média de idade de todos os clientes é de 33.25 anos


## 4. Substituir valores faltantes na coluna Cidade por 'Desconhecido'

In [34]:
df['Cidade'] = df['Cidade'].fillna('Desconhecido')

## 5. Calcular a soma total das vendas (ignorando valores nulos)

In [ ]:
soma_total_vendas = df['Vendas'].sum()
print("A soma total das vendas é de R$", soma_total_vendas)